Column length
neutrinoceros/inifix pull request #73
Opened 2021-10-27 14:45 UTC by vdbma

2021-10-27 15:28 UTC, neutrinoceros submitted a review, later dismissed
Thanks for this patch. Ultimately I want to merge this but we'll need a couple iterations to get there. Here are my first comments.

2021-11-17 14:50 UTC, neutrinoceros commented on inifix/format.py
> +        return "'" + self.name + "'"
I'm not convinced this class is necessary yet, but the first three method look a lot like you just want to inherit from `str`
```suggestion
class Parameter(str):
```

2021-11-17 14:50 UTC, neutrinoceros commented on inifix/format.py
> +        r"""Similar to ljust, but will always add a whitespace \s at the end of the string, for the ini file to be usable"""
```suggestion
    def ljust(self, width) -> str:
        r"""Similar to str.ljust, but always append a whitespace '\s', for the ini file to be usable"""
```

2021-11-17 15:03 UTC, neutrinoceros commented on inifix/format.py
> +                + f"longer than user specified column length ({column_length}). "  # I don't like this
something like this
```
", ".join([f"{_!r}" for _ in long_params])
```

2021-11-18 10:49 UTC, neutrinoceros reviewed
We're getting there, thanks your sustained effort !

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +    ):  # in this case, ljust already appended a whitespace : no need to append one
Seems clear enough without a comment
```suggestion
    if len(string) < width:
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +            ]
one-letter variable names are ok for iteration and list comprehensions, and preferable to splitting this over 3 lines just to comply to black
```suggestion
            long_parameters = [p for p in parameters if len(p) >= column_length]
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +                )
This doesn't seem worth the additional complexity IMO
```suggestion
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +                + f" is/are longer than user specified column length ({column_length}). "
Systematic plural is preferred, and whitespace should always be trailing, not leading
```suggestion
                + f"are longer than user specified column length ({column_length}). "
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +            column_length = None
Looks to me that this doesn't have any effect
```suggestion
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +                new_line += f"{ljust(parameters[parameter_count],padded_name_col_size)}{'  '.join(values[parameter_count])}"
Don't push the limits of fstrings' power to make your code readable :-p
```suggestion
                new_line += ljust(parameters[parameter_count], padded_name_col_size)
                new_line += "  ".join(values[parameter_count])
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +def ljust(string: str, width: int) -> str:
`_` is to signal that I don't want this function to be considered public API
Also, many other functions/methods in inifix use `s` as a first argument when it's a str (it's ugly, but consistency prevails, and it won't matter in the future when these arguments become positional-only)
```suggestion
def _ljust(s: str, width: int) -> str:
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +DEFAULT_PADDING_SIZE = 4
Well, all of them are "default" now, aren't they ?
```suggestion
PADDING_SIZE = 4
```

2021-11-18 10:49 UTC, neutrinoceros commented on inifix/format.py
> +                + "\n".join([f"{long_parameter}" for long_parameter in long_parameters])
Unless I'm reading this wrong this is now equivalent
```suggestion
                + "\n".join(long_parameters)
```

2021-11-18 12:48 UTC, vdbma commented on inifix/format.py
> +    return readable_name
isn't it best to have only one `return` in a function or is that just old school thing ?

2021-11-18 12:49 UTC, neutrinoceros commented on inifix/format.py
> +                + "are longer than user specified column length ({column_length}). "
Oops
```suggestion
                + f"are longer than user specified column length ({column_length}). "
```

2021-11-18 12:54 UTC, neutrinoceros commented on inifix/format.py
> +    parameter_count = 0
Took me a couple reads to figure out why I didn't like this variable: it's not a counter, it's an index
```suggestion
    parameter_idx = 0
```

2021-11-18 12:54 UTC, neutrinoceros commented on inifix/format.py
> +                parameter_count += 1  # all the lists are not of the same length : len(parameters) == len(values) != len(contents) == len(comments)
Actually I found this comment more confusing that helping :/
```suggestion
                parameter_idx+= 1
```

2021-11-18 12:57 UTC, neutrinoceros commented on inifix/format.py
> +                "parameter/s:\n"
```suggestion
                "Parameters:\n"
```

2021-11-18 12:59 UTC, neutrinoceros commented on README.md
> +* Use the `--column-length` flag to specify the length of the first column (including right padding). Be aware that if the specified value is less or equal than the length of the longtest parameter n
How about naming it `--name-column-size` ?

2021-11-18 13:07 UTC, neutrinoceros commented on inifix/format.py
> +    return readable_name
I once religiously considered it best practice but changed my mind after I realised that it didn't help me produce clearer code in general, and I've never really got the hang of it. Avoiding binding variables that are immediately returned however is still something I value

2021-11-18 13:08 UTC, neutrinoceros commented on inifix/format.py
> +    return readable_name
(note that returning in the `if` branch makes the `else` statement useless, but I don't have strong opinions on wether it's best to keep it or not, suit yourself)

2021-11-18 13:09 UTC, vdbma commented on inifix/format.py
> +    return readable_name
Fair enough !

2021-11-18 13:13 UTC, neutrinoceros commented on inifix/format.py
> +            values.append(value)
I think that this will behave weirdly with empty lines. It should suffice to set `content = _normalize_whitespace(content)` above

2021-11-18 15:42 UTC, neutrinoceros commented on inifix/format.py
> +            )
Now I anticipate this warning could be extremely annoying as well as not terribly useful.
If we change the name of the argument (again, sorry!) to `minimal_name_column_size`, then we don't need to warn users.

2021-11-18 15:43 UTC, neutrinoceros commented on README.md
> +* Use the `--column-length` flag to specify the length of the first column (including right padding). Be aware that if the specified value is less or equal than the length of the longtest parameter n
@vdbma this has fallen behind

2021-11-19 17:17 UTC, neutrinoceros reviewed
does commenting retrigger test ?

2021-11-21 12:16 UTC, neutrinoceros commented
Sorry about the multiple closing/reopening, the problem with silent CI was on my side. It's finally running !

2021-11-23 14:27 UTC, neutrinoceros requested changes

2021-11-23 14:27 UTC, neutrinoceros commented on README.md
```suggestion
* Use `--name-column-size <n>` to specify the length of the first column (including right padding).
Names longer this value will not be aligned, but whitespace separating them from values will be minimised.
```

2021-11-23 14:27 UTC, neutrinoceros commented on tests/test_format.py
> +def test_exact_format_with_column_size_flag(flag, capsys, tmp_path):
This is not a flag
```suggestion
@pytest.mark.parametrize("size", ["10", "20", "50"])
@pytest.mark.filterwarnings(r"ignore:^The following parameters\n")
def test_exact_format_with_column_size_flag(size, capsys, tmp_path):
```

2021-11-23 14:27 UTC, neutrinoceros commented on tests/test_format.py
> +    ret = main([str(target), "-i", "--name-column-size", flag])
```suggestion
    ret = main([str(target), "-i", "--name-column-size", size])
```

2021-11-23 14:27 UTC, neutrinoceros commented on tests/test_format.py
> +    expected = (DATA_DIR / f"format-column-size-out-{flag}.ini").read_text()
```suggestion
    expected = (DATA_DIR / f"format-column-size-out-{size}.ini").read_text()
```

2021-11-23 14:27 UTC, neutrinoceros commented on tests/data/format-column-size-out.ini
> +[A first section]
looks like this file isn't used in the test anymore (as well as its corresponding "in" file ?)

2021-11-23 14:32 UTC, vdbma commented on tests/data/format-column-size-out.ini
> +[A first section]
yes i noticed, thx (fixed in f42fc2970a6898828e289bc953a002652ff3e850)

2021-11-23 14:49 UTC, neutrinoceros approved these changes

2021-11-23 14:49 UTC, merged